version: '3'

vars:
  TAILWIND_CMD:
    sh: command -v tailwindcss >/dev/null 2>&1 && echo "tailwindcss" || echo "npx tailwindcss@latest"

tasks:
  # Development Tools
  templ:
    desc: Run templ with integrated server and hot reload
    cmds:
      - go tool templ generate --watch --proxy="http://localhost:8090" --cmd="go run ./cmd/docs/main.go" --open-browser=true

  shiki-highlighter:
    desc: Start shiki syntax highlighter service
    dir: shiki
    cmds:
      - npm start

  tailwind-clean:
    desc: Clean tailwind output
    cmds:
      - "{{.TAILWIND_CMD}} -i ./assets/css/input.css -o ./assets/css/output.css --clean"

  tailwind-watch:
    desc: Run tailwindcss in watch mode
    cmds:
      - "{{.TAILWIND_CMD}} -i ./assets/css/input.css -o ./assets/css/output.css --watch"

  minify-js-components:
    desc: Minify and watch JavaScript component files
    cmds:
      - |
        npx esbuild \
        internal/components/avatar/avatar.js \
        internal/components/calendar/calendar.js \
        internal/components/carousel/carousel.js \
        internal/components/chart/chart.js \
        internal/components/code/code.js \
        internal/components/collapsible/collapsible.js \
        internal/components/copybutton/copybutton.js \
        internal/components/datepicker/datepicker.js \
        internal/components/dialog/dialog.js \
        internal/components/dropdown/dropdown.js \
        internal/components/input/input.js \
        internal/components/inputotp/inputotp.js \
        internal/components/label/label.js \
        internal/components/popover/popover.js \
        internal/components/progress/progress.js \
        internal/components/rating/rating.js \
        internal/components/selectbox/selectbox.js \
        internal/components/sidebar/sidebar.js \
        internal/components/slider/slider.js \
        internal/components/tabs/tabs.js \
        internal/components/tagsinput/tagsinput.js \
        internal/components/textarea/textarea.js \
        internal/components/timepicker/timepicker.js \
        internal/components/toast/toast.js \
        --minify \
        --watch \
        --bundle \
        --outdir=internal/components \
        --out-extension:.js=.min.js

  dev:
    desc: Start development server with hot reload
    deps:
      - tailwind-clean
    cmds:
      - task --parallel tailwind-watch templ shiki-highlighter minify-js-components

  # Build & Validation
  templ-generate:
    desc: Compile templ files into Go
    cmds:
      - go tool templ generate

  render-showcases:
    desc: Render showcase components into out/showcase/
    cmds:
      - go run ./cmd/render-showcases

  build-html:
    desc: Build static showcase HTML
    deps:
      - templ-generate
      - render-showcases
    cmds:
      - echo "✅ Static showcase HTML rendered to ./out"

  lint-html:
    desc: Lint HTML output using ESLint
    cmds:
      - npx eslint --fix "out/**/*.html" --ext .html

  validate-html:
    desc: Run full pipeline (build + lint)
    deps:
      - build-html
      - lint-html

  # Generators
  generate-sitemap:
    desc: Generate sitemap.xml
    cmds:
      - go run ./cmd/sitemap/main.go --baseurl="https://templui.io" --routes="./cmd/docs/main.go" --output="./static/sitemap.xml"

  generate-icons:
    desc: Generate icon definitions
    cmds:
      - go run cmd/icongen/main.go

  install-compinstall:
    desc: Install compinstall tool
    cmds:
      - go install ./cmd/compinstall
